"""add message status fields

Revision ID: 00098a531dbc
Revises: 7232d4563672
Create Date: 2026-04-09 17:17:37.466971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00098a531dbc'
down_revision = '7232d4563672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.drop_column('read_at')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
