"""report approval and director remarks

Revision ID: 134bc90d4361
Revises: 6f40d705ba4d
Create Date: 2026-09-30 16:46:05.551083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134bc90d4361'
down_revision = '6f40d705ba4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('general_remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officer_id', 'report_date', name='uq_report_approval')
    )
    with op.batch_alter_table('report_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_approvals_officer_id'), ['officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_approvals_report_date'), ['report_date'], unique=False)

    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_remark', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('director_remark_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('director_remark_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['director_remark_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('director_remark_at')
        batch_op.drop_column('director_remark_by')
        batch_op.drop_column('director_remark')

    with op.batch_alter_table('report_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_approvals_report_date'))
        batch_op.drop_index(batch_op.f('ix_report_approvals_officer_id'))

    op.drop_table('report_approvals')
    # ### end Alembic commands ###
