"""added columns for tracking original plan and interest rate for tahe sake of waived loans defaults

Revision ID: 1568d4d41550
Revises: bbea88138881
Create Date: 2026-06-15 10:36:55.686778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1568d4d41550'
down_revision = 'bbea88138881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_repayment_plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('original_interest_rate', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('original_interest_rate')
        batch_op.drop_column('original_repayment_plan')

    # ### end Alembic commands ###
