"""added funds choosing in loan approval process

Revision ID: 171e197c6804
Revises: 61bfaf12bb0b
Create Date: 2026-01-17 17:57:52.389565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171e197c6804'
down_revision = '61bfaf12bb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ownership_type', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'investors', ['investor_id'], ['id'])

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('investor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'investors', ['investor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('investor_id')
        batch_op.drop_column('funding_source')

    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ownership_type')
        batch_op.drop_column('investor_id')

    # ### end Alembic commands ###
