"""Make recipient_id nullable for group messages

Revision ID: 1943dd5968fa
Revises: 05783c9c254a
Create Date: 2026-07-23 19:37:02.849654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1943dd5968fa'
down_revision = '05783c9c254a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
