"""updated investor model to add backward compatibility

Revision ID: 2322ce3f179e
Revises: fa574b5bdb5c
Create Date: 2026-01-31 17:37:19.165810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2322ce3f179e'
down_revision = 'fa574b5bdb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
