"""added call feature

Revision ID: 23c52fb732d7
Revises: be97ebd4dd3e
Create Date: 2026-06-20 18:00:00.568240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c52fb732d7'
down_revision = 'be97ebd4dd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('caller_id', sa.Integer(), nullable=False),
    sa.Column('callee_id', sa.Integer(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('group_participants', sa.JSON(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['callee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['private_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_logs')
    # ### end Alembic commands ###
