"""updated loans.py

Revision ID: 263cd1a40aae
Revises: 9264aad08781
Create Date: 2025-12-01 10:34:19.751137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263cd1a40aae'
down_revision = '9264aad08781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
