"""updated investor  model

Revision ID: 33d7b41a1978
Revises: d5e469243f21
Create Date: 2025-01-30 10:12:12.345678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d7b41a1978'
down_revision = 'd5e469243f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        # Add columns as nullable first
        batch_op.add_column(sa.Column('initial_investment', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('current_investment', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_topups', sa.Numeric(precision=12, scale=2), nullable=True))
    
    # Update existing rows: set initial_investment and current_investment to the value of investment_amount
    op.execute("""
        UPDATE investors 
        SET initial_investment = COALESCE(investment_amount, 0),
            current_investment = COALESCE(investment_amount, 0),
            total_topups = 0
    """)
    
    # Now make the columns NOT NULL
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.alter_column('initial_investment', nullable=False)
        batch_op.alter_column('current_investment', nullable=False)
        batch_op.alter_column('total_topups', nullable=False)
        batch_op.drop_column('investment_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    
    # Copy data back
    op.execute("""
        UPDATE investors 
        SET investment_amount = current_investment
    """)
    
    # Make investment_amount NOT NULL
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.alter_column('investment_amount', nullable=False)
        batch_op.drop_column('total_topups')
        batch_op.drop_column('current_investment')
        batch_op.drop_column('initial_investment')
    # ### end Alembic commands ###