"""add flagged_loans

Revision ID: 385822fc0e8a
Revises: 432632aa006a
Create Date: 2026-06-09 09:04:57.872829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385822fc0e8a'
down_revision = '432632aa006a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flagged_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('flagged_by', sa.Integer(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('previous_officer_id', sa.Integer(), nullable=True),
    sa.Column('valuer_notes', sa.Text(), nullable=True),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['previous_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flagged_loans')
    # ### end Alembic commands ###
