"""updated the user model to add biometrics

Revision ID: 3e277bf5542d
Revises: ab19c3439ce5
Create Date: 2026-04-13 19:16:53.382435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e277bf5542d'
down_revision = 'ab19c3439ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webauthn_credential_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('webauthn_public_key', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_sign_count', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['webauthn_credential_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('webauthn_sign_count')
        batch_op.drop_column('webauthn_public_key')
        batch_op.drop_column('webauthn_credential_id')

    # ### end Alembic commands ###
