"""added flaggedloan note

Revision ID: 3eeccd5d5f2b
Revises: ee9cf6d9475d
Create Date: 2026-09-12 15:17:08.135415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eeccd5d5f2b'
down_revision = 'ee9cf6d9475d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flagged_loan_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'user_id', name='uq_flagged_loan_user')
    )
    with op.batch_alter_table('flagged_loan_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flagged_loan_notes_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flagged_loan_notes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flagged_loan_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flagged_loan_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_flagged_loan_notes_loan_id'))

    op.drop_table('flagged_loan_notes')
    # ### end Alembic commands ###
