"""add day assignments and enhanced client assignments

Revision ID: 432632aa006a
Revises: 1cf2be72a121
Create Date: 2026-06-04 14:32:40.526422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432632aa006a'
down_revision = '1cf2be72a121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', name='uq_user_day')
    )
    with op.batch_alter_table('client_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('assigned_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('override_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'])
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('override_reason')
        batch_op.drop_column('assigned_by')
        batch_op.drop_column('assignment_type')

    op.drop_table('day_assignments')
    # ### end Alembic commands ###
