"""updated transaction model

Revision ID: 43aa17006a0f
Revises: 05c4685e9648
Create Date: 2025-10-09 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '43aa17006a0f'
down_revision = '05c4685e9648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns with nullable=True first
    op.add_column('transactions', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('method', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('mpesa_reference', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('merchant_request_id', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('checkout_request_id', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('date', sa.DateTime(), nullable=True))
    
    # Update existing data
    op.execute("UPDATE transactions SET type = transaction_type WHERE transaction_type IS NOT NULL")
    op.execute("UPDATE transactions SET type = 'payment' WHERE type IS NULL")  # default for any nulls
    
    op.execute("UPDATE transactions SET method = payment_method WHERE payment_method IS NOT NULL")
    op.execute("UPDATE transactions SET method = 'cash' WHERE method IS NULL")  # default for null payment_method
    
    op.execute("UPDATE transactions SET status = 'completed' WHERE status IS NULL")  # assume existing are completed
    
    op.execute("UPDATE transactions SET mpesa_reference = mpesa_receipt WHERE mpesa_receipt IS NOT NULL")
    
    op.execute("UPDATE transactions SET date = created_at WHERE created_at IS NOT NULL")
    
    # Now make NOT NULL where required
    op.alter_column('transactions', 'type', nullable=False)
    op.alter_column('transactions', 'method', nullable=False)
    op.alter_column('transactions', 'status', nullable=False)
    
    # Change amount type from NUMERIC to Float
    op.alter_column('transactions', 'amount',
                    existing_type=sa.NUMERIC(precision=10, scale=2),
                    type_=sa.Float(),
                    existing_nullable=False)
    
    # Drop old columns
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'mpesa_receipt')
    op.drop_column('transactions', 'payment_method')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back old columns
    op.add_column('transactions', sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False))
    op.add_column('transactions', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('transactions', sa.Column('mpesa_receipt', sa.VARCHAR(length=50), nullable=True))
    op.add_column('transactions', sa.Column('payment_method', sa.VARCHAR(length=20), nullable=True))
    
    # Copy data back
    op.execute("UPDATE transactions SET transaction_type = type")
    op.execute("UPDATE transactions SET created_at = date")
    op.execute("UPDATE transactions SET mpesa_receipt = mpesa_reference")
    op.execute("UPDATE transactions SET payment_method = method")
    
    # Drop new columns
    op.drop_column('transactions', 'phone_number')
    op.drop_column('transactions', 'checkout_request_id')
    op.drop_column('transactions', 'merchant_request_id')
    op.drop_column('transactions', 'mpesa_reference')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'method')
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'date')
    
    # Revert amount type
    op.alter_column('transactions', 'amount',
                    existing_type=sa.Float(),
                    type_=sa.NUMERIC(precision=10, scale=2),
                    existing_nullable=False)
    
    # ### end Alembic commands ###