"""fixing claimed livestock location

Revision ID: 47545111c19f
Revises: a7f3c9d8e2b1
Create Date: 2025-12-19 10:03:16.456501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47545111c19f'
down_revision = 'a7f3c9d8e2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_client_id_number'))
        batch_op.drop_index(batch_op.f('idx_client_phone'))

    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_livestock_client_id'))
        batch_op.drop_index(batch_op.f('idx_livestock_status'))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_loan_client_id'))
        batch_op.drop_index(batch_op.f('idx_loan_disbursement_date'))
        batch_op.drop_index(batch_op.f('idx_loan_due_date'))
        batch_op.drop_index(batch_op.f('idx_loan_livestock_id'))
        batch_op.drop_index(batch_op.f('idx_loan_status'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transaction_created_at'))
        batch_op.drop_index(batch_op.f('idx_transaction_loan_id'))
        batch_op.drop_index(batch_op.f('idx_transaction_type'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_transaction_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_transaction_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_loan_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_loan_livestock_id'), ['livestock_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_loan_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_loan_disbursement_date'), ['disbursement_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_loan_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_livestock_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_livestock_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_client_phone'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_client_id_number'), ['id_number'], unique=False)

    # ### end Alembic commands ###
