"""add payroll_excluded

Revision ID: 495f67fead95
Revises: 5f805d19d3d6
Create Date: 2026-10-09 11:54:38.447309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495f67fead95'
down_revision = '5f805d19d3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_excluded', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('payroll_excluded')

    # ### end Alembic commands ###
