"""updated investor model and investor return to process 40% monthly insteado f 10% weekly

Revision ID: 524d351c486e
Revises: e97f4b8ee85c
Create Date: 2026-01-22 14:27:16.313365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524d351c486e'
down_revision = 'e97f4b8ee85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_early_withdrawal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('early_withdrawal_fee', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor_returns', schema=None) as batch_op:
        batch_op.drop_column('early_withdrawal_fee')
        batch_op.drop_column('is_early_withdrawal')

    # ### end Alembic commands ###
