"""separeted description and location storage for livestock gallery

Revision ID: 5d716be81941
Revises: 171e197c6804
Create Date: 2026-01-17 22:32:55.930040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d716be81941'
down_revision = '171e197c6804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
