"""empty message

Revision ID: 5f805d19d3d6
Revises: 525db03122d8
Create Date: 2026-10-05 12:59:33.637719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f805d19d3d6'
down_revision = '525db03122d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_market_value', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('forced_value', sa.Numeric(precision=15, scale=2), nullable=True))

    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_report_comments_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_comments_officer_id'), ['officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_comments_report_date'), ['report_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_comments_report_date'))
        batch_op.drop_index(batch_op.f('ix_report_comments_officer_id'))
        batch_op.drop_index(batch_op.f('ix_report_comments_loan_id'))
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.drop_column('forced_value')
        batch_op.drop_column('current_market_value')

    # ### end Alembic commands ###
