"""added email

Revision ID: 61bfaf12bb0b
Revises: 9b21d4f925ed
Create Date: 2026-01-13 14:06:32.910032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bfaf12bb0b'
down_revision = '9b21d4f925ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('current_period_interest_paid')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_investor_id_fkey'), type_='foreignkey')
        batch_op.drop_column('investor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_investor_id_fkey'), 'investors', ['investor_id'], ['id'])

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_period_interest_paid', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))

    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
