"""updated relationships

Revision ID: 624fbca8c819
Revises: 524d351c486e
Create Date: 2026-01-22 14:54:00.495915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624fbca8c819'
down_revision = '524d351c486e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
