"""Updated transaction model added topup and edit loan

Revision ID: 6913e5b21399
Revises: aa12e1f4c4c1
Create Date: 2025-11-02 23:13:30.639381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6913e5b21399'
down_revision = 'aa12e1f4c4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
