"""Add repayment_plan to loans

Revision ID: 7232d4563672
Revises: 59a07557804d
Create Date: 2026-04-06 13:59:57.528163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7232d4563672'
down_revision = '59a07557804d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repayment_plan', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('repayment_plan')

    # ### end Alembic commands ###
