"""updated loan ledger

Revision ID: 74955342b553
Revises: 8836ec585b3c
Create Date: 2026-09-18 17:10:30.972000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74955342b553'
down_revision = '8836ec585b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_loan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sequence', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('period_label', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_loan_ledger_root_loan_id'), ['root_loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_ledger_sequence'), ['sequence'], unique=False)
        batch_op.create_foreign_key(None, 'loans', ['root_loan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_ledger', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_loan_ledger_sequence'))
        batch_op.drop_index(batch_op.f('ix_loan_ledger_root_loan_id'))
        batch_op.drop_column('period_label')
        batch_op.drop_column('sequence')
        batch_op.drop_column('root_loan_id')

    # ### end Alembic commands ###
