"""Add investor features

Revision ID: 7a0ac3bc32fc
Revises: 624fbca8c819
Create Date: 2026-01-24 08:47:25.970679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0ac3bc32fc'
down_revision = '624fbca8c819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
