"""add credit_balance for advance returns

Revision ID: 852f2c6b2fd4
Revises: f9eaf00f5f70
Create Date: 2026-03-18 12:50:00.770592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852f2c6b2fd4'
down_revision = 'f9eaf00f5f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_balance', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.drop_column('credit_balance')

    # ### end Alembic commands ###
