"""add promissory_notes table

Revision ID: 8836ec585b3c
Revises: ee67c940ef78
Create Date: 2026-09-16 13:09:19.965567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8836ec585b3c'
down_revision = 'ee67c940ef78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promissory_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('amount_to_pay', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promissory_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promissory_notes_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_promissory_notes_loan_id'), ['loan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promissory_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promissory_notes_loan_id'))
        batch_op.drop_index(batch_op.f('ix_promissory_notes_issued_at'))

    op.drop_table('promissory_notes')
    # ### end Alembic commands ###
