"""Add loan parent/root fields, last_accrual_recorded, and loan_ledger table

Revision ID: 886d451c2a51
Revises: 9425f35fb018
Create Date: 2026-05-18 12:35:41.430401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886d451c2a51'
down_revision = '9425f35fb018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('principal_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalty_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_outstanding', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_ledger_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_ledger_loan_id'), ['loan_id'], unique=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_loan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('root_loan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_accrual_recorded', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_loans_root_loan_id'), ['root_loan_id'], unique=False)
        batch_op.create_foreign_key(None, 'loans', ['parent_loan_id'], ['id'])
        batch_op.create_foreign_key(None, 'loans', ['root_loan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_loans_root_loan_id'))
        batch_op.drop_column('last_accrual_recorded')
        batch_op.drop_column('root_loan_id')
        batch_op.drop_column('parent_loan_id')

    with op.batch_alter_table('loan_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_ledger_loan_id'))
        batch_op.drop_index(batch_op.f('ix_loan_ledger_event_date'))

    op.drop_table('loan_ledger')
    # ### end Alembic commands ###
