"""upadted admin.py and payments.py to fix client payment processing

Revision ID: 90e8929eaaa7
Revises: 263cd1a40aae
Create Date: 2025-12-01 14:02:25.284654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e8929eaaa7'
down_revision = '263cd1a40aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
