"""Add default values for principal tracking fields

Revision ID: 9264aad08781
Revises: 6913e5b21399
Create Date: 2025-12-01 09:18:20.677436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9264aad08781'
down_revision = '6913e5b21399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('current_principal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('current_principal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###
