"""Add webauthn fields and challenge table

Revision ID: 92be38ce4aac
Revises: 3e277bf5542d
Create Date: 2026-04-21 23:08:38.979148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92be38ce4aac'
down_revision = '3e277bf5542d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webauthn_challenges',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webauthn_transports', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('webauthn_transports')

    op.drop_table('webauthn_challenges')
    # ### end Alembic commands ###
