"""add message_attachments table

Revision ID: 9425f35fb018
Revises: 9933449b169c
Create Date: 2026-05-12 19:56:23.427260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9425f35fb018'
down_revision = '9933449b169c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.drop_column('attachment_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_data', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('message_attachments')
    # ### end Alembic commands ###
