"""add attachment_data

Revision ID: 9933449b169c
Revises: d35699ea5493
Create Date: 2026-05-09 22:07:42.948546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9933449b169c'
down_revision = 'd35699ea5493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.drop_column('attachment_data')

    # ### end Alembic commands ###
