"""added prepaid interest in the loan model

Revision ID: ab19c3439ce5
Revises: 00098a531dbc
Create Date: 2026-04-10 15:49:38.596615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab19c3439ce5'
down_revision = '00098a531dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_prepaid_period', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('interest_prepaid_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('interest_prepaid_amount')
        batch_op.drop_column('interest_prepaid_period')

    # ### end Alembic commands ###
