"""updated report to store the figures

Revision ID: b918dd35c05f
Revises: 1568d4d41550
Create Date: 2026-06-15 16:30:07.266789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b918dd35c05f'
down_revision = '1568d4d41550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_principal', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('unpaid_interest', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_balance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('repayment_plan', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.drop_column('repayment_plan')
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('total_balance')
        batch_op.drop_column('unpaid_interest')
        batch_op.drop_column('current_principal')

    # ### end Alembic commands ###
