"""updated transaction model to add investor statement and top ups in receits and statements

Revision ID: d5e469243f21
Revises: 7a0ac3bc32fc
Create Date: 2026-01-30 15:39:03.119627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e469243f21'
down_revision = '7a0ac3bc32fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('loan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'investors', ['investor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('loan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('investor_id')

    # ### end Alembic commands ###
