"""added init in investor model

Revision ID: d65c6564ab1b
Revises: 5d716be81941
Create Date: 2026-01-20 17:51:53.334182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65c6564ab1b'
down_revision = '5d716be81941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
