"""added next of kin details in client model

Revision ID: e94348708747
Revises: 1ccae0ab180f
Create Date: 2026-09-29 16:19:54.337271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94348708747'
down_revision = '1ccae0ab180f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_of_kin_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_relationship', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('next_of_kin_relationship')
        batch_op.drop_column('next_of_kin_id')
        batch_op.drop_column('next_of_kin_name')

    # ### end Alembic commands ###
