"""updated the user model to allow username and password changing for investor accounts

Revision ID: e97f4b8ee85c
Revises: d65c6564ab1b
Create Date: 2026-01-21 15:19:50.251865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97f4b8ee85c'
down_revision = 'd65c6564ab1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
