"""add edited/updated_at to private_messages

Revision ID: ee67c940ef78
Revises: 3eeccd5d5f2b
Create Date: 2026-09-15 16:27:40.302995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee67c940ef78'
down_revision = '3eeccd5d5f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
