"""add group read tracking

Revision ID: ee9cf6d9475d
Revises: 1943dd5968fa
Create Date: 2026-07-27 13:42:00.528443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9cf6d9475d'
down_revision = '1943dd5968fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_read_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_group_read')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_column('last_read_at')

    op.drop_table('group_read_status')
    # ### end Alembic commands ###
