"""updated investor model to have investment_amount

Revision ID: f29ba4faf175
Revises: f586419c177a
Create Date: 2026-02-02 22:49:17.074251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29ba4faf175'
down_revision = 'f586419c177a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_amount', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.drop_column('investment_amount')

    # ### end Alembic commands ###
