"""updated chat feature to edit and reply messages

Revision ID: f73a03593fec
Revises: cb3dc4812b18
Create Date: 2026-03-30 21:42:37.611910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73a03593fec'
down_revision = 'cb3dc4812b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'comments', ['parent_id'], ['id'])

    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_messages', schema=None) as batch_op:
        batch_op.drop_column('attachment_name')
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_url')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('edited')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
