"""added outstanding return to allow early return processing

Revision ID: f9eaf00f5f70
Revises: eae1086f3887
Create Date: 2026-03-17 17:47:10.431246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9eaf00f5f70'
down_revision = 'eae1086f3887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outstanding_returns', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.drop_column('outstanding_returns')

    # ### end Alembic commands ###
